-- Comprehensive test dataset for jdk_clean.
-- Generated by actually running every scenario through the real
-- application service layer (not hand-typed SQL), then dumping the
-- resulting rows -- every total, discount figure, and status
-- combination here is exactly what the real app produced, not a guess.
--
-- Covers: full happy-path order (feasibility -> auto-quotation ->
-- order -> auto-scheduled production -> auto-created delivery note ->
-- delivered), an order+deal cancelled mid-flight, a raw-material
-- shortfall requiring Sales override, a product with no BOM
-- configured (bom_missing), leftover finished-goods stock recognized
-- by a later feasibility check (covered_by_stock), a quotation and a
-- purchase order each awaiting admin approval (large discount / large
-- amount), a real MRP shortage auto-drafting a purchase order, and
-- overdue orders/POs/feasibility checks flagged for admin review.
--
-- Assumes backend/schema.sql (and all migrations) has already been
-- applied. Every table this file touches is TRUNCATEd before inserting,
-- so this is safe to re-run even against a database that already has
-- data in these specific tables -- it will be replaced, not duplicated
-- or collided with. Tables this file doesn't reference are left alone.

-- Login as any of these once loaded (all use the same password):
--   demo_admin       / Demo@12345   (role: admin)
--   demo_manager     / Demo@12345   (role: manager)
--   demo_sales       / Demo@12345   (role: staff, department: sales)
--   demo_procurement / Demo@12345   (role: staff, department: procurement)
--   demo_warehouse   / Demo@12345   (role: staff, department: warehouse)
-- Change these passwords once you're done testing.

SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;

-- Children first, then parents (order doesn't matter with checks off, but
-- keeping it FK-safe means this also works if checks are ever left on).
-- Safe to re-run: everything below is truncated before insert, same as
-- running this against a genuinely fresh database.
TRUNCATE TABLE quotation_details;
TRUNCATE TABLE quotations;
TRUNCATE TABLE order_details;
TRUNCATE TABLE orders;
TRUNCATE TABLE delivery_note_lines;
TRUNCATE TABLE delivery_notes;
TRUNCATE TABLE purchase_order_lines;
TRUNCATE TABLE purchase_orders;
TRUNCATE TABLE production_schedules;
TRUNCATE TABLE feasibility_lines;
TRUNCATE TABLE feasibility_checks;
TRUNCATE TABLE deals;
TRUNCATE TABLE bom_lines;
TRUNCATE TABLE supplier_materials;
TRUNCATE TABLE finished_goods_inventory;
TRUNCATE TABLE raw_material_inventory;
TRUNCATE TABLE stock_movements;
TRUNCATE TABLE products;
TRUNCATE TABLE machines;
TRUNCATE TABLE raw_materials;
TRUNCATE TABLE suppliers;
TRUNCATE TABLE customers;
TRUNCATE TABLE refresh_tokens;
TRUNCATE TABLE audit_log;
TRUNCATE TABLE users;
TRUNCATE TABLE settings;


-- users (5 rows). department_id is looked up by code rather than
-- hardcoded, since departments now lives in the departments master table
-- (seeded by schema.sql) instead of being a fixed ENUM -- see
-- migrations/2026-08-31_add_departments.sql.
INSERT INTO users (id, username, email, password_hash, full_name, phone, avatar_filename, department_id, signature_filename, role, is_active, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'demo_admin', 'demo.admin@jdk-test.local', '$2b$12$sMuhFv0neMvZ9E6RWUVMMOh9uitgB/fysAlNAEJFasp7S9a.DAxnG', 'Demo Admin', NULL, NULL, NULL, NULL, 'admin', 1, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO users (id, username, email, password_hash, full_name, phone, avatar_filename, department_id, signature_filename, role, is_active, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'demo_manager', 'demo.manager@jdk-test.local', '$2b$12$sMuhFv0neMvZ9E6RWUVMMOh9uitgB/fysAlNAEJFasp7S9a.DAxnG', 'Demo Manager', NULL, NULL, NULL, NULL, 'manager', 1, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO users (id, username, email, password_hash, full_name, phone, avatar_filename, department_id, signature_filename, role, is_active, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 'demo_sales', 'demo.sales@jdk-test.local', '$2b$12$sMuhFv0neMvZ9E6RWUVMMOh9uitgB/fysAlNAEJFasp7S9a.DAxnG', 'Demo Sales Rep', NULL, NULL, (SELECT id FROM departments WHERE code = 'sales'), NULL, 'staff', 1, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO users (id, username, email, password_hash, full_name, phone, avatar_filename, department_id, signature_filename, role, is_active, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (4, 'demo_procurement', 'demo.procurement@jdk-test.local', '$2b$12$sMuhFv0neMvZ9E6RWUVMMOh9uitgB/fysAlNAEJFasp7S9a.DAxnG', 'Demo Procurement Lead', NULL, NULL, (SELECT id FROM departments WHERE code = 'procurement'), NULL, 'staff', 1, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO users (id, username, email, password_hash, full_name, phone, avatar_filename, department_id, signature_filename, role, is_active, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (5, 'demo_warehouse', 'demo.warehouse@jdk-test.local', '$2b$12$sMuhFv0neMvZ9E6RWUVMMOh9uitgB/fysAlNAEJFasp7S9a.DAxnG', 'Demo Warehouse Lead', NULL, NULL, (SELECT id FROM departments WHERE code = 'warehouse'), NULL, 'staff', 1, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);

-- customers (3 rows)
INSERT INTO customers (id, code, name, contact_person, email, phone, billing_address, shipping_address, city, country, credit_limit, payment_terms_days, status, notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'CUST-001', 'Gulf Fabrication Co.', NULL, 'ap@gulf-fab-test.local', '+965-2222-0001', NULL, NULL, NULL, NULL, 50000, 30, 'active', NULL, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO customers (id, code, name, contact_person, email, phone, billing_address, shipping_address, city, country, credit_limit, payment_terms_days, status, notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'CUST-002', 'Kuwait Steel Traders', NULL, 'accounts@kw-steel-test.local', '+965-2222-0002', NULL, NULL, NULL, NULL, 15000, 30, 'active', NULL, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO customers (id, code, name, contact_person, email, phone, billing_address, shipping_address, city, country, credit_limit, payment_terms_days, status, notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 'CUST-003', 'Al Salem Contracting', NULL, 'finance@alsalem-test.local', '+965-2222-0003', NULL, NULL, NULL, NULL, 8000, 30, 'active', NULL, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);

-- suppliers (2 rows)
INSERT INTO suppliers (id, code, name, contact_person, email, phone, address, city, country, payment_terms_days, mode_of_supply, rating, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'SUP-001', 'Gulf Metal Supply', NULL, 'sales@gulf-metal-test.local', '+965-2333-0001', NULL, NULL, NULL, 30, NULL, NULL, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO suppliers (id, code, name, contact_person, email, phone, address, city, country, payment_terms_days, mode_of_supply, rating, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'SUP-002', 'Kuwait Raw Materials LLC', NULL, 'orders@kw-raw-test.local', '+965-2333-0002', NULL, NULL, NULL, 45, NULL, NULL, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);

-- raw_materials (3 rows)
INSERT INTO raw_materials (id, code, name, unit, reorder_point, default_supplier_id, unit_cost, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'RM-001', 'Steel Sheet 2mm', 'kg', 100, NULL, 8.5, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO raw_materials (id, code, name, unit, reorder_point, default_supplier_id, unit_cost, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'RM-002', 'Aluminium Rod 10mm', 'kg', 50, NULL, 12, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO raw_materials (id, code, name, unit, reorder_point, default_supplier_id, unit_cost, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 'RM-003', 'Powder Coat Paint', 'litre', 20, NULL, 15.75, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);

-- machines (2 rows)
INSERT INTO machines (id, code, name, capacity_hours_per_day, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'MC-001', 'CNC Press A', 8, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO machines (id, code, name, capacity_hours_per_day, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'MC-002', 'CNC Press B', 8, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);

-- products (4 rows)
INSERT INTO products (id, code, name, unit, product_type, selling_price, machine_id, production_hours_per_unit, workers_required, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'PRD-001', 'Steel Bracket - Type A', 'pcs', 'finished_good', 45, 1, 0.5, 2, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO products (id, code, name, unit, product_type, selling_price, machine_id, production_hours_per_unit, workers_required, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'PRD-002', 'Aluminium Housing - Standard', 'pcs', 'finished_good', 120, 2, 1.5, 1, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO products (id, code, name, unit, product_type, selling_price, machine_id, production_hours_per_unit, workers_required, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 'PRD-003', 'Custom Powder-Coated Panel', 'pcs', 'finished_good', 75, 1, 1, 1, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO products (id, code, name, unit, product_type, selling_price, machine_id, production_hours_per_unit, workers_required, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (4, 'PRD-004', 'Legacy Assembly (formula not set up)', 'pcs', 'finished_good', 200, NULL, NULL, NULL, 'active', '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);

-- bom_lines (3 rows)
INSERT INTO bom_lines (id, parent_product_id, component_type, component_id, quantity, unit, scrap_percent, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 1, 'raw_material', 1, 2, 'kg', 5, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO bom_lines (id, parent_product_id, component_type, component_id, quantity, unit, scrap_percent, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 2, 'raw_material', 2, 3.5, 'kg', 3, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO bom_lines (id, parent_product_id, component_type, component_id, quantity, unit, scrap_percent, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 2, 'raw_material', 3, 0.2, 'litre', 2, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);

-- supplier_materials (4 rows)
INSERT INTO supplier_materials (id, supplier_id, raw_material_id, max_supply_quantity, lead_time_days, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 1, 1, 5000, 7, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO supplier_materials (id, supplier_id, raw_material_id, max_supply_quantity, lead_time_days, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 1, 2, 1000, 10, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO supplier_materials (id, supplier_id, raw_material_id, max_supply_quantity, lead_time_days, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 2, 2, 800, 5, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);
INSERT INTO supplier_materials (id, supplier_id, raw_material_id, max_supply_quantity, lead_time_days, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (4, 2, 3, 2000, 4, '2026-08-01 10:46:45', NULL, '2026-08-01 10:46:45', NULL, NULL);

-- deals (8 rows)
INSERT INTO deals (id, deal_number, customer_id, furthest_stage, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'DEAL-00001', 1, 'delivery', 'open', '2026-08-01 10:46:45', 3, '2026-08-01 10:46:46', 5, NULL);
INSERT INTO deals (id, deal_number, customer_id, furthest_stage, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'DEAL-00002', 2, 'production', 'cancelled', '2026-08-01 10:46:46', 3, '2026-08-01 10:46:46', 3, NULL);
INSERT INTO deals (id, deal_number, customer_id, furthest_stage, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 'DEAL-00003', 1, 'quotation', 'open', '2026-08-01 10:46:46', 3, '2026-08-01 10:46:46', 2, NULL);
INSERT INTO deals (id, deal_number, customer_id, furthest_stage, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (4, 'DEAL-00004', 3, 'feasibility', 'open', '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', NULL, NULL);
INSERT INTO deals (id, deal_number, customer_id, furthest_stage, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (5, 'DEAL-00005', 2, 'delivery', 'cancelled', '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);
INSERT INTO deals (id, deal_number, customer_id, furthest_stage, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (6, 'DEAL-00006', 3, 'quotation', 'open', '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);
INSERT INTO deals (id, deal_number, customer_id, furthest_stage, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (7, 'DEAL-00007', 1, 'quotation', 'open', '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', NULL, NULL);
INSERT INTO deals (id, deal_number, customer_id, furthest_stage, status, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (8, 'DEAL-00008', 3, 'delivery', 'open', '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);

-- feasibility_checks (7 rows)
INSERT INTO feasibility_checks (id, feasibility_number, customer_id, deal_id, status, required_by_date, checked_at, exception_reason, exception_by, close_reason, notes, admin_review_required, admin_review_reason, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'FSB-00001', 1, 1, 'converted', '2026-08-15', '2026-08-01 10:46:46.012462', NULL, NULL, NULL, 'Standard bracket order.', 0, NULL, NULL, NULL, NULL, '2026-08-01 10:46:45', 3, '2026-08-01 10:46:46', 3, NULL);
INSERT INTO feasibility_checks (id, feasibility_number, customer_id, deal_id, status, required_by_date, checked_at, exception_reason, exception_by, close_reason, notes, admin_review_required, admin_review_reason, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'FSB-00002', 2, 2, 'converted', '2026-08-11', '2026-08-01 10:46:46.806657', NULL, NULL, NULL, 'Trial order, may not proceed.', 0, NULL, NULL, NULL, NULL, '2026-08-01 10:46:46', 3, '2026-08-01 10:46:46', 3, NULL);
INSERT INTO feasibility_checks (id, feasibility_number, customer_id, deal_id, status, required_by_date, checked_at, exception_reason, exception_by, close_reason, notes, admin_review_required, admin_review_reason, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 'FSB-00003', 1, 3, 'converted', '2026-08-08', '2026-08-01 10:46:46.987749', 'Customer accepted a 2-week delay for the material to arrive.', 2, NULL, 'Urgent -- customer wants this fast.', 1, 'override', NULL, NULL, NULL, '2026-08-01 10:46:46', 3, '2026-08-01 10:46:46', 2, NULL);
INSERT INTO feasibility_checks (id, feasibility_number, customer_id, deal_id, status, required_by_date, checked_at, exception_reason, exception_by, close_reason, notes, admin_review_required, admin_review_reason, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (4, 'FSB-00004', 3, 4, 'exception_pending', '2026-08-22', '2026-08-01 10:46:47.015331', NULL, NULL, NULL, 'New product -- formula not set up yet.', 1, 'stale_open', NULL, NULL, NULL, '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);
INSERT INTO feasibility_checks (id, feasibility_number, customer_id, deal_id, status, required_by_date, checked_at, exception_reason, exception_by, close_reason, notes, admin_review_required, admin_review_reason, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (5, 'FSB-00005', 2, 5, 'converted', '2026-08-15', '2026-08-01 10:46:47.030665', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);
INSERT INTO feasibility_checks (id, feasibility_number, customer_id, deal_id, status, required_by_date, checked_at, exception_reason, exception_by, close_reason, notes, admin_review_required, admin_review_reason, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (6, 'FSB-00006', 3, 6, 'converted', '2026-08-06', '2026-08-01 10:46:47.124355', NULL, NULL, NULL, 'Small repeat order.', 0, NULL, NULL, NULL, NULL, '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);
INSERT INTO feasibility_checks (id, feasibility_number, customer_id, deal_id, status, required_by_date, checked_at, exception_reason, exception_by, close_reason, notes, admin_review_required, admin_review_reason, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (7, 'FSB-00007', 3, 8, 'converted', '2026-08-04', '2026-08-01 10:46:47.304994', NULL, NULL, NULL, 'Customer needs this urgently.', 0, NULL, NULL, NULL, NULL, '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);

-- feasibility_lines (7 rows)
INSERT INTO feasibility_lines (id, feasibility_id, product_id, quantity, covered_by_stock, bom_missing, is_feasible, shortfall_json, capacity_ok, capacity_shortfall_json) VALUES (1, 1, 1, 100, NULL, NULL, 1, NULL, 1, NULL);
INSERT INTO feasibility_lines (id, feasibility_id, product_id, quantity, covered_by_stock, bom_missing, is_feasible, shortfall_json, capacity_ok, capacity_shortfall_json) VALUES (2, 2, 1, 20, NULL, NULL, 1, NULL, 1, NULL);
INSERT INTO feasibility_lines (id, feasibility_id, product_id, quantity, covered_by_stock, bom_missing, is_feasible, shortfall_json, capacity_ok, capacity_shortfall_json) VALUES (3, 3, 2, 10, NULL, NULL, 0, '[{"raw_material_id": 2, "code": "RM-002", "name": "Aluminium Rod 10mm", "unit": "kg", "required": 36.05, "on_hand": 15.0, "shortfall": 21.05}]', 1, NULL);
INSERT INTO feasibility_lines (id, feasibility_id, product_id, quantity, covered_by_stock, bom_missing, is_feasible, shortfall_json, capacity_ok, capacity_shortfall_json) VALUES (4, 4, 3, 30, NULL, 1, 0, NULL, NULL, NULL);
INSERT INTO feasibility_lines (id, feasibility_id, product_id, quantity, covered_by_stock, bom_missing, is_feasible, shortfall_json, capacity_ok, capacity_shortfall_json) VALUES (5, 5, 1, 50, NULL, NULL, 1, NULL, 1, NULL);
INSERT INTO feasibility_lines (id, feasibility_id, product_id, quantity, covered_by_stock, bom_missing, is_feasible, shortfall_json, capacity_ok, capacity_shortfall_json) VALUES (6, 6, 1, 20, 20, NULL, 1, NULL, NULL, NULL);
INSERT INTO feasibility_lines (id, feasibility_id, product_id, quantity, covered_by_stock, bom_missing, is_feasible, shortfall_json, capacity_ok, capacity_shortfall_json) VALUES (7, 7, 1, 15, 15, NULL, 1, NULL, NULL, NULL);

-- orders (4 rows)
INSERT INTO orders (id, order_number, customer_id, deal_id, order_date, requested_delivery_date, confirmed_delivery_date, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, close_reason, approved_at, approved_by, admin_review_required, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'ORD-00001', 1, 1, '2026-08-01', NULL, NULL, 'delivered', 4500, 0, 0, 4500, 'Converted from quotation QTN-00001.', NULL, NULL, NULL, 0, NULL, NULL, NULL, '2026-08-01 10:46:46', 3, '2026-08-01 10:46:46', 5, NULL);
INSERT INTO orders (id, order_number, customer_id, deal_id, order_date, requested_delivery_date, confirmed_delivery_date, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, close_reason, approved_at, approved_by, admin_review_required, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'ORD-00002', 2, 2, '2026-08-01', NULL, NULL, 'cancelled', 900, 0, 0, 900, 'Converted from quotation QTN-00002.', 'Customer postponed the project indefinitely.', NULL, NULL, 0, NULL, NULL, NULL, '2026-08-01 10:46:46', 3, '2026-08-01 10:46:46', 3, NULL);
INSERT INTO orders (id, order_number, customer_id, deal_id, order_date, requested_delivery_date, confirmed_delivery_date, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, close_reason, approved_at, approved_by, admin_review_required, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 'ORD-00003', 2, 5, '2026-08-01', NULL, NULL, 'cancelled', 2250, 0, 0, 2250, 'Converted from quotation QTN-00004.', 'Customer cancelled after production finished; product kept in stock for resale.', NULL, NULL, 0, NULL, NULL, NULL, '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);
INSERT INTO orders (id, order_number, customer_id, deal_id, order_date, requested_delivery_date, confirmed_delivery_date, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, close_reason, approved_at, approved_by, admin_review_required, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (4, 'ORD-00004', 3, 8, '2026-08-01', '2026-07-27', NULL, 'ready_to_ship', 675, 0, 0, 675, 'Converted from quotation QTN-00007.', NULL, NULL, NULL, 1, NULL, NULL, NULL, '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);

-- order_details (4 rows)
INSERT INTO order_details (id, order_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (1, 1, 1, 100, 45, 0, 4500);
INSERT INTO order_details (id, order_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (2, 2, 1, 20, 45, 0, 900);
INSERT INTO order_details (id, order_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (3, 3, 1, 50, 45, 0, 2250);
INSERT INTO order_details (id, order_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (4, 4, 1, 15, 45, 0, 675);

-- purchase_orders (2 rows)
INSERT INTO purchase_orders (id, po_number, supplier_id, order_date, expected_delivery_date, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, auto_created, cancel_reason, approved_at, approved_by, admin_review_required, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'PO-00001', 2, '2026-08-01', '2026-08-06', 'draft', 685.2, 0, 0, 685.2, 'Auto-drafted from an MRP shortage. Review quantities and pricing before sending.', 1, NULL, NULL, NULL, 1, NULL, NULL, NULL, '2026-08-01 10:46:47', 4, '2026-08-01 10:46:47', NULL, NULL);
INSERT INTO purchase_orders (id, po_number, supplier_id, order_date, expected_delivery_date, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, auto_created, cancel_reason, approved_at, approved_by, admin_review_required, admin_reviewed_at, admin_reviewed_by, admin_review_notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'PO-00002', 1, '2026-08-01', '2026-08-11', 'draft', 4250, 0, 0, 4250, 'Bulk steel restock ahead of Q3 demand.', 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, '2026-08-01 10:46:47', 4, '2026-08-01 10:46:47', NULL, NULL);

-- purchase_order_lines (2 rows)
INSERT INTO purchase_order_lines (id, purchase_order_id, raw_material_id, quantity, unit_price, discount_percent, line_total, received_quantity) VALUES (1, 1, 2, 57.099999999999994, 12, 0, 685.2, 0);
INSERT INTO purchase_order_lines (id, purchase_order_id, raw_material_id, quantity, unit_price, discount_percent, line_total, received_quantity) VALUES (2, 2, 1, 500, 8.5, 0, 4250, 0);

-- delivery_notes (3 rows)
INSERT INTO delivery_notes (id, delivery_note_number, order_id, delivery_date, status, auto_created, cancel_reason, notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'DN-00001', 1, '2026-08-01', 'issued', 1, NULL, 'Auto-created when the order became ready to ship.', '2026-08-01 10:46:46', 5, '2026-08-01 10:46:46', 5, NULL);
INSERT INTO delivery_notes (id, delivery_note_number, order_id, delivery_date, status, auto_created, cancel_reason, notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'DN-00002', 3, '2026-08-01', 'draft', 1, NULL, 'Auto-created when the order became ready to ship.', '2026-08-01 10:46:47', 5, '2026-08-01 10:46:47', NULL, NULL);
INSERT INTO delivery_notes (id, delivery_note_number, order_id, delivery_date, status, auto_created, cancel_reason, notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 'DN-00003', 4, '2026-08-01', 'draft', 1, NULL, 'Auto-created when the order became ready to ship.', '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', NULL, NULL);

-- delivery_note_lines (3 rows)
INSERT INTO delivery_note_lines (id, delivery_note_id, product_id, quantity_delivered) VALUES (1, 1, 1, 100);
INSERT INTO delivery_note_lines (id, delivery_note_id, product_id, quantity_delivered) VALUES (2, 2, 1, 50);
INSERT INTO delivery_note_lines (id, delivery_note_id, product_id, quantity_delivered) VALUES (3, 3, 1, 15);

-- quotations (7 rows)
INSERT INTO quotations (id, quotation_number, customer_id, deal_id, quotation_date, valid_until, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, converted_order_id, feasibility_id, auto_created, close_reason, approved_at, approved_by, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'QTN-00001', 1, 1, '2026-08-01', NULL, 'converted', 4500, 0, 0, 4500, 'Auto-created from feasibility check FSB-00001.', 1, 1, 1, NULL, NULL, NULL, '2026-08-01 10:46:46', 3, '2026-08-01 10:46:46', 3, NULL);
INSERT INTO quotations (id, quotation_number, customer_id, deal_id, quotation_date, valid_until, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, converted_order_id, feasibility_id, auto_created, close_reason, approved_at, approved_by, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'QTN-00002', 2, 2, '2026-08-01', NULL, 'converted', 900, 0, 0, 900, 'Auto-created from feasibility check FSB-00002.', 2, 2, 1, NULL, NULL, NULL, '2026-08-01 10:46:46', 3, '2026-08-01 10:46:46', 3, NULL);
INSERT INTO quotations (id, quotation_number, customer_id, deal_id, quotation_date, valid_until, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, converted_order_id, feasibility_id, auto_created, close_reason, approved_at, approved_by, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 'QTN-00003', 1, 3, '2026-08-01', NULL, 'sent', 1200, 0, 0, 1200, 'Auto-created from feasibility check FSB-00003.', NULL, 3, 1, NULL, NULL, NULL, '2026-08-01 10:46:46', 2, '2026-08-01 10:46:47', 3, NULL);
INSERT INTO quotations (id, quotation_number, customer_id, deal_id, quotation_date, valid_until, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, converted_order_id, feasibility_id, auto_created, close_reason, approved_at, approved_by, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (4, 'QTN-00004', 2, 5, '2026-08-01', NULL, 'converted', 2250, 0, 0, 2250, 'Auto-created from feasibility check FSB-00005.', 3, 5, 1, NULL, NULL, NULL, '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);
INSERT INTO quotations (id, quotation_number, customer_id, deal_id, quotation_date, valid_until, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, converted_order_id, feasibility_id, auto_created, close_reason, approved_at, approved_by, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (5, 'QTN-00005', 3, 6, '2026-08-01', NULL, 'draft', 900, 0, 0, 900, 'Auto-created from feasibility check FSB-00006.', NULL, 6, 1, NULL, NULL, NULL, '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', NULL, NULL);
INSERT INTO quotations (id, quotation_number, customer_id, deal_id, quotation_date, valid_until, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, converted_order_id, feasibility_id, auto_created, close_reason, approved_at, approved_by, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (6, 'QTN-00006', 1, 7, '2026-08-01', '2026-08-31', 'draft', 1800, 20, 360, 1440, 'Bulk order -- customer negotiated a steep discount, needs sign-off.', NULL, NULL, 0, NULL, NULL, NULL, '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', NULL, NULL);
INSERT INTO quotations (id, quotation_number, customer_id, deal_id, quotation_date, valid_until, status, subtotal_amount, discount_percent, discount_amount, total_amount, notes, converted_order_id, feasibility_id, auto_created, close_reason, approved_at, approved_by, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (7, 'QTN-00007', 3, 8, '2026-08-01', NULL, 'converted', 675, 0, 0, 675, 'Auto-created from feasibility check FSB-00007.', 4, 7, 1, NULL, NULL, NULL, '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 3, NULL);

-- quotation_details (7 rows)
INSERT INTO quotation_details (id, quotation_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (1, 1, 1, 100, 45, 0, 4500);
INSERT INTO quotation_details (id, quotation_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (2, 2, 1, 20, 45, 0, 900);
INSERT INTO quotation_details (id, quotation_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (3, 3, 2, 10, 120, 0, 1200);
INSERT INTO quotation_details (id, quotation_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (4, 4, 1, 50, 45, 0, 2250);
INSERT INTO quotation_details (id, quotation_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (5, 5, 1, 20, 45, 0, 900);
INSERT INTO quotation_details (id, quotation_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (6, 6, 2, 15, 120, 0, 1800);
INSERT INTO quotation_details (id, quotation_id, product_id, quantity, unit_price, discount_percent, line_total) VALUES (7, 7, 1, 15, 45, 0, 675);

-- production_schedules (4 rows)
INSERT INTO production_schedules (id, batch_number, product_id, machine_id, order_id, planned_quantity, produced_quantity, scheduled_start, scheduled_end, actual_start, actual_end, status, auto_scheduled, cancel_reason, notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (1, 'PB-00001', 1, 1, 1, 100, 100, '2026-08-01', '2026-08-07', '2026-08-01 10:46:46.344461', '2026-08-01 10:46:46.442977', 'completed', 1, NULL, 'Auto-scheduled on confirmation of ORD-00001.', '2026-08-01 10:46:46', 3, '2026-08-01 10:46:46', 5, NULL);
INSERT INTO production_schedules (id, batch_number, product_id, machine_id, order_id, planned_quantity, produced_quantity, scheduled_start, scheduled_end, actual_start, actual_end, status, auto_scheduled, cancel_reason, notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (2, 'PB-00002', 1, 1, 2, 20, 0, '2026-08-01', '2026-08-02', NULL, NULL, 'cancelled', 1, 'Order ORD-00002 was cancelled: Customer postponed the project indefinitely.', 'Auto-scheduled on confirmation of ORD-00002.', '2026-08-01 10:46:46', 3, '2026-08-01 10:46:46', 3, NULL);
INSERT INTO production_schedules (id, batch_number, product_id, machine_id, order_id, planned_quantity, produced_quantity, scheduled_start, scheduled_end, actual_start, actual_end, status, auto_scheduled, cancel_reason, notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (3, 'PB-00003', 1, 1, 3, 50, 50, '2026-08-01', '2026-08-04', '2026-08-01 10:46:47.070926', '2026-08-01 10:46:47.087467', 'completed', 1, NULL, 'Auto-scheduled on confirmation of ORD-00003.', '2026-08-01 10:46:47', 3, '2026-08-01 10:46:47', 5, NULL);
INSERT INTO production_schedules (id, batch_number, product_id, machine_id, order_id, planned_quantity, produced_quantity, scheduled_start, scheduled_end, actual_start, actual_end, status, auto_scheduled, cancel_reason, notes, created_at, created_by, updated_at, updated_by, deleted_at) VALUES (4, 'PB-00004', 2, 2, NULL, 20, 0, '2026-08-01', '2026-08-05', NULL, NULL, 'planned', 0, NULL, NULL, '2026-08-01 10:46:47', 5, '2026-08-01 10:46:47', NULL, NULL);

-- raw_material_inventory (3 rows)
INSERT INTO raw_material_inventory (id, raw_material_id, quantity_on_hand, quantity_reserved, updated_at) VALUES (1, 1, 1685, 0, '2026-08-01 10:46:47');
INSERT INTO raw_material_inventory (id, raw_material_id, quantity_on_hand, quantity_reserved, updated_at) VALUES (2, 2, 15, 0, '2026-08-01 10:46:45');
INSERT INTO raw_material_inventory (id, raw_material_id, quantity_on_hand, quantity_reserved, updated_at) VALUES (3, 3, 500, 0, '2026-08-01 10:46:45');

-- finished_goods_inventory (3 rows)
INSERT INTO finished_goods_inventory (id, product_id, quantity_on_hand, quantity_reserved, updated_at) VALUES (1, 1, 50, 15, '2026-08-01 10:46:47');
INSERT INTO finished_goods_inventory (id, product_id, quantity_on_hand, quantity_reserved, updated_at) VALUES (2, 2, 0, 0, '2026-08-01 10:46:46');
INSERT INTO finished_goods_inventory (id, product_id, quantity_on_hand, quantity_reserved, updated_at) VALUES (3, 3, 0, 0, '2026-08-01 10:46:47');

-- stock_movements (5 rows)
INSERT INTO stock_movements (id, item_type, item_id, movement_type, quantity, reference_type, reference_id, notes, created_at, created_by) VALUES (1, 'raw_material', 1, 'issue', -210, 'production_schedule', 1, 'Consumed by batch PB-00001', '2026-08-01 10:46:46', 5);
INSERT INTO stock_movements (id, item_type, item_id, movement_type, quantity, reference_type, reference_id, notes, created_at, created_by) VALUES (2, 'product', 1, 'receipt', 100, 'production_schedule', 1, 'Produced by batch PB-00001', '2026-08-01 10:46:46', 5);
INSERT INTO stock_movements (id, item_type, item_id, movement_type, quantity, reference_type, reference_id, notes, created_at, created_by) VALUES (3, 'product', 1, 'issue', -100, 'order', 1, 'Shipped against ORD-00001', '2026-08-01 10:46:46', 5);
INSERT INTO stock_movements (id, item_type, item_id, movement_type, quantity, reference_type, reference_id, notes, created_at, created_by) VALUES (4, 'raw_material', 1, 'issue', -105, 'production_schedule', 3, 'Consumed by batch PB-00003', '2026-08-01 10:46:47', 5);
INSERT INTO stock_movements (id, item_type, item_id, movement_type, quantity, reference_type, reference_id, notes, created_at, created_by) VALUES (5, 'product', 1, 'receipt', 50, 'production_schedule', 3, 'Produced by batch PB-00003', '2026-08-01 10:46:47', 5);

-- settings (8 rows)
INSERT INTO settings (id, setting_key, setting_value, updated_at) VALUES (1, 'factory_total_workers', '10', '2026-08-01 10:46:45');
INSERT INTO settings (id, setting_key, setting_value, updated_at) VALUES (2, 'factory_workday_hours', '8', '2026-08-01 10:46:45');
INSERT INTO settings (id, setting_key, setting_value, updated_at) VALUES (4, 'large_po_approval_threshold', '2000', '2026-08-01 10:46:45');
INSERT INTO settings (id, setting_key, setting_value, updated_at) VALUES (5, 'large_discount_approval_threshold', '15', '2026-08-01 10:46:45');
INSERT INTO settings (id, setting_key, setting_value, updated_at) VALUES (6, 'auto_create_quotation_from_feasibility', 'true', '2026-08-01 10:46:45');
INSERT INTO settings (id, setting_key, setting_value, updated_at) VALUES (7, 'auto_schedule_production_on_order_confirm', 'true', '2026-08-01 10:46:45');
INSERT INTO settings (id, setting_key, setting_value, updated_at) VALUES (8, 'auto_create_delivery_note_on_ready_to_ship', 'true', '2026-08-01 10:46:45');
INSERT INTO settings (id, setting_key, setting_value, updated_at) VALUES (9, 'auto_draft_purchase_orders_from_mrp', 'true', '2026-08-01 10:46:45');

SET FOREIGN_KEY_CHECKS = 1;